spring.application.name=N

spring.datasource.url=jdbc:postgresql://localhost:5432/n_project
spring.datasource.username=me
spring.datasource.password=me

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true